### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by jztech101** [TechCavern/WaveSite#7]
Cause why not?

**Comment by ZL1LAC** [comment]
Sup?  Add me on discord.

**Comment by jztech101** [comment]
@dh47 I don't use discord anymore. If you want to talk, come on freenode #techcavern

**Comment by s0cks** [comment]
React!!!! <3

**Comment by jztech101** [comment]
@s0cks maybe. :)

**Comment by s0cks** [comment]
I have been loving react, however it can be a pain to set up for the long run haha. I recommend react + webpack because it makes everything as simple as possible lol

**Comment by jztech101** [comment]
@s0cks yeah, but I really like this theme lmao. So I went with bootstrap instead.
